[package]
name = "self-organizing-map-lab"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
nalgebra = { version = "0.33.2", features = ["rand"] }
csv = "1.3.1" 
clearscreen = "3.0.0"
plotters = "0.3.7"